
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorkSpaceMembers` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model WorkSpaceMembers
 * 
 */
export type WorkSpaceMembersModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkSpaceMembersPayload>

export type AggregateWorkSpaceMembers = {
  _count: WorkSpaceMembersCountAggregateOutputType | null
  _avg: WorkSpaceMembersAvgAggregateOutputType | null
  _sum: WorkSpaceMembersSumAggregateOutputType | null
  _min: WorkSpaceMembersMinAggregateOutputType | null
  _max: WorkSpaceMembersMaxAggregateOutputType | null
}

export type WorkSpaceMembersAvgAggregateOutputType = {
  id: number | null
}

export type WorkSpaceMembersSumAggregateOutputType = {
  id: number | null
}

export type WorkSpaceMembersMinAggregateOutputType = {
  id: number | null
  membership_Id: string | null
  role: $Enums.Role | null
  joinedAt: Date | null
  workspaceId: string | null
  user_Id: string | null
}

export type WorkSpaceMembersMaxAggregateOutputType = {
  id: number | null
  membership_Id: string | null
  role: $Enums.Role | null
  joinedAt: Date | null
  workspaceId: string | null
  user_Id: string | null
}

export type WorkSpaceMembersCountAggregateOutputType = {
  id: number
  membership_Id: number
  role: number
  joinedAt: number
  workspaceId: number
  user_Id: number
  _all: number
}


export type WorkSpaceMembersAvgAggregateInputType = {
  id?: true
}

export type WorkSpaceMembersSumAggregateInputType = {
  id?: true
}

export type WorkSpaceMembersMinAggregateInputType = {
  id?: true
  membership_Id?: true
  role?: true
  joinedAt?: true
  workspaceId?: true
  user_Id?: true
}

export type WorkSpaceMembersMaxAggregateInputType = {
  id?: true
  membership_Id?: true
  role?: true
  joinedAt?: true
  workspaceId?: true
  user_Id?: true
}

export type WorkSpaceMembersCountAggregateInputType = {
  id?: true
  membership_Id?: true
  role?: true
  joinedAt?: true
  workspaceId?: true
  user_Id?: true
  _all?: true
}

export type WorkSpaceMembersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkSpaceMembers to aggregate.
   */
  where?: Prisma.WorkSpaceMembersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkSpaceMembers to fetch.
   */
  orderBy?: Prisma.WorkSpaceMembersOrderByWithRelationInput | Prisma.WorkSpaceMembersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkSpaceMembersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkSpaceMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkSpaceMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorkSpaceMembers
  **/
  _count?: true | WorkSpaceMembersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorkSpaceMembersAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorkSpaceMembersSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkSpaceMembersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkSpaceMembersMaxAggregateInputType
}

export type GetWorkSpaceMembersAggregateType<T extends WorkSpaceMembersAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkSpaceMembers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkSpaceMembers[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkSpaceMembers[P]>
}




export type WorkSpaceMembersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkSpaceMembersWhereInput
  orderBy?: Prisma.WorkSpaceMembersOrderByWithAggregationInput | Prisma.WorkSpaceMembersOrderByWithAggregationInput[]
  by: Prisma.WorkSpaceMembersScalarFieldEnum[] | Prisma.WorkSpaceMembersScalarFieldEnum
  having?: Prisma.WorkSpaceMembersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkSpaceMembersCountAggregateInputType | true
  _avg?: WorkSpaceMembersAvgAggregateInputType
  _sum?: WorkSpaceMembersSumAggregateInputType
  _min?: WorkSpaceMembersMinAggregateInputType
  _max?: WorkSpaceMembersMaxAggregateInputType
}

export type WorkSpaceMembersGroupByOutputType = {
  id: number
  membership_Id: string
  role: $Enums.Role
  joinedAt: Date
  workspaceId: string
  user_Id: string
  _count: WorkSpaceMembersCountAggregateOutputType | null
  _avg: WorkSpaceMembersAvgAggregateOutputType | null
  _sum: WorkSpaceMembersSumAggregateOutputType | null
  _min: WorkSpaceMembersMinAggregateOutputType | null
  _max: WorkSpaceMembersMaxAggregateOutputType | null
}

export type GetWorkSpaceMembersGroupByPayload<T extends WorkSpaceMembersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkSpaceMembersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkSpaceMembersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkSpaceMembersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkSpaceMembersGroupByOutputType[P]>
      }
    >
  >



export type WorkSpaceMembersWhereInput = {
  AND?: Prisma.WorkSpaceMembersWhereInput | Prisma.WorkSpaceMembersWhereInput[]
  OR?: Prisma.WorkSpaceMembersWhereInput[]
  NOT?: Prisma.WorkSpaceMembersWhereInput | Prisma.WorkSpaceMembersWhereInput[]
  id?: Prisma.IntFilter<"WorkSpaceMembers"> | number
  membership_Id?: Prisma.StringFilter<"WorkSpaceMembers"> | string
  role?: Prisma.EnumRoleFilter<"WorkSpaceMembers"> | $Enums.Role
  joinedAt?: Prisma.DateTimeFilter<"WorkSpaceMembers"> | Date | string
  workspaceId?: Prisma.StringFilter<"WorkSpaceMembers"> | string
  user_Id?: Prisma.StringFilter<"WorkSpaceMembers"> | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type WorkSpaceMembersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  membership_Id?: Prisma.SortOrder
  role?: Prisma.SortOrder
  joinedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  user_Id?: Prisma.SortOrder
  workspace?: Prisma.WorkspaceOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type WorkSpaceMembersWhereUniqueInput = Prisma.AtLeast<{
  membership_Id?: string
  AND?: Prisma.WorkSpaceMembersWhereInput | Prisma.WorkSpaceMembersWhereInput[]
  OR?: Prisma.WorkSpaceMembersWhereInput[]
  NOT?: Prisma.WorkSpaceMembersWhereInput | Prisma.WorkSpaceMembersWhereInput[]
  id?: Prisma.IntFilter<"WorkSpaceMembers"> | number
  role?: Prisma.EnumRoleFilter<"WorkSpaceMembers"> | $Enums.Role
  joinedAt?: Prisma.DateTimeFilter<"WorkSpaceMembers"> | Date | string
  workspaceId?: Prisma.StringFilter<"WorkSpaceMembers"> | string
  user_Id?: Prisma.StringFilter<"WorkSpaceMembers"> | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "membership_Id">

export type WorkSpaceMembersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  membership_Id?: Prisma.SortOrder
  role?: Prisma.SortOrder
  joinedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  user_Id?: Prisma.SortOrder
  _count?: Prisma.WorkSpaceMembersCountOrderByAggregateInput
  _avg?: Prisma.WorkSpaceMembersAvgOrderByAggregateInput
  _max?: Prisma.WorkSpaceMembersMaxOrderByAggregateInput
  _min?: Prisma.WorkSpaceMembersMinOrderByAggregateInput
  _sum?: Prisma.WorkSpaceMembersSumOrderByAggregateInput
}

export type WorkSpaceMembersScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkSpaceMembersScalarWhereWithAggregatesInput | Prisma.WorkSpaceMembersScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkSpaceMembersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkSpaceMembersScalarWhereWithAggregatesInput | Prisma.WorkSpaceMembersScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"WorkSpaceMembers"> | number
  membership_Id?: Prisma.StringWithAggregatesFilter<"WorkSpaceMembers"> | string
  role?: Prisma.EnumRoleWithAggregatesFilter<"WorkSpaceMembers"> | $Enums.Role
  joinedAt?: Prisma.DateTimeWithAggregatesFilter<"WorkSpaceMembers"> | Date | string
  workspaceId?: Prisma.StringWithAggregatesFilter<"WorkSpaceMembers"> | string
  user_Id?: Prisma.StringWithAggregatesFilter<"WorkSpaceMembers"> | string
}

export type WorkSpaceMembersCreateInput = {
  id?: number
  membership_Id?: string
  role?: $Enums.Role
  joinedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutMembersInput
  user: Prisma.UserCreateNestedOneWithoutWorkspaceMembersInput
}

export type WorkSpaceMembersUncheckedCreateInput = {
  id?: number
  membership_Id?: string
  role?: $Enums.Role
  joinedAt?: Date | string
  workspaceId: string
  user_Id: string
}

export type WorkSpaceMembersUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  membership_Id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutMembersNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutWorkspaceMembersNestedInput
}

export type WorkSpaceMembersUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  membership_Id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  user_Id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorkSpaceMembersCreateManyInput = {
  id?: number
  membership_Id?: string
  role?: $Enums.Role
  joinedAt?: Date | string
  workspaceId: string
  user_Id: string
}

export type WorkSpaceMembersUpdateManyMutationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  membership_Id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkSpaceMembersUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  membership_Id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  user_Id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorkSpaceMembersListRelationFilter = {
  every?: Prisma.WorkSpaceMembersWhereInput
  some?: Prisma.WorkSpaceMembersWhereInput
  none?: Prisma.WorkSpaceMembersWhereInput
}

export type WorkSpaceMembersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorkSpaceMembersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  membership_Id?: Prisma.SortOrder
  role?: Prisma.SortOrder
  joinedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  user_Id?: Prisma.SortOrder
}

export type WorkSpaceMembersAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type WorkSpaceMembersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  membership_Id?: Prisma.SortOrder
  role?: Prisma.SortOrder
  joinedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  user_Id?: Prisma.SortOrder
}

export type WorkSpaceMembersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  membership_Id?: Prisma.SortOrder
  role?: Prisma.SortOrder
  joinedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  user_Id?: Prisma.SortOrder
}

export type WorkSpaceMembersSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type WorkSpaceMembersCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.WorkSpaceMembersCreateWithoutUserInput, Prisma.WorkSpaceMembersUncheckedCreateWithoutUserInput> | Prisma.WorkSpaceMembersCreateWithoutUserInput[] | Prisma.WorkSpaceMembersUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkSpaceMembersCreateOrConnectWithoutUserInput | Prisma.WorkSpaceMembersCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.WorkSpaceMembersCreateManyUserInputEnvelope
  connect?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
}

export type WorkSpaceMembersUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.WorkSpaceMembersCreateWithoutUserInput, Prisma.WorkSpaceMembersUncheckedCreateWithoutUserInput> | Prisma.WorkSpaceMembersCreateWithoutUserInput[] | Prisma.WorkSpaceMembersUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkSpaceMembersCreateOrConnectWithoutUserInput | Prisma.WorkSpaceMembersCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.WorkSpaceMembersCreateManyUserInputEnvelope
  connect?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
}

export type WorkSpaceMembersUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.WorkSpaceMembersCreateWithoutUserInput, Prisma.WorkSpaceMembersUncheckedCreateWithoutUserInput> | Prisma.WorkSpaceMembersCreateWithoutUserInput[] | Prisma.WorkSpaceMembersUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkSpaceMembersCreateOrConnectWithoutUserInput | Prisma.WorkSpaceMembersCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.WorkSpaceMembersUpsertWithWhereUniqueWithoutUserInput | Prisma.WorkSpaceMembersUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.WorkSpaceMembersCreateManyUserInputEnvelope
  set?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  disconnect?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  delete?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  connect?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  update?: Prisma.WorkSpaceMembersUpdateWithWhereUniqueWithoutUserInput | Prisma.WorkSpaceMembersUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.WorkSpaceMembersUpdateManyWithWhereWithoutUserInput | Prisma.WorkSpaceMembersUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.WorkSpaceMembersScalarWhereInput | Prisma.WorkSpaceMembersScalarWhereInput[]
}

export type WorkSpaceMembersUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.WorkSpaceMembersCreateWithoutUserInput, Prisma.WorkSpaceMembersUncheckedCreateWithoutUserInput> | Prisma.WorkSpaceMembersCreateWithoutUserInput[] | Prisma.WorkSpaceMembersUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkSpaceMembersCreateOrConnectWithoutUserInput | Prisma.WorkSpaceMembersCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.WorkSpaceMembersUpsertWithWhereUniqueWithoutUserInput | Prisma.WorkSpaceMembersUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.WorkSpaceMembersCreateManyUserInputEnvelope
  set?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  disconnect?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  delete?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  connect?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  update?: Prisma.WorkSpaceMembersUpdateWithWhereUniqueWithoutUserInput | Prisma.WorkSpaceMembersUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.WorkSpaceMembersUpdateManyWithWhereWithoutUserInput | Prisma.WorkSpaceMembersUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.WorkSpaceMembersScalarWhereInput | Prisma.WorkSpaceMembersScalarWhereInput[]
}

export type WorkSpaceMembersCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.WorkSpaceMembersCreateWithoutWorkspaceInput, Prisma.WorkSpaceMembersUncheckedCreateWithoutWorkspaceInput> | Prisma.WorkSpaceMembersCreateWithoutWorkspaceInput[] | Prisma.WorkSpaceMembersUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.WorkSpaceMembersCreateOrConnectWithoutWorkspaceInput | Prisma.WorkSpaceMembersCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.WorkSpaceMembersCreateManyWorkspaceInputEnvelope
  connect?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
}

export type WorkSpaceMembersUncheckedCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.WorkSpaceMembersCreateWithoutWorkspaceInput, Prisma.WorkSpaceMembersUncheckedCreateWithoutWorkspaceInput> | Prisma.WorkSpaceMembersCreateWithoutWorkspaceInput[] | Prisma.WorkSpaceMembersUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.WorkSpaceMembersCreateOrConnectWithoutWorkspaceInput | Prisma.WorkSpaceMembersCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.WorkSpaceMembersCreateManyWorkspaceInputEnvelope
  connect?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
}

export type WorkSpaceMembersUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.WorkSpaceMembersCreateWithoutWorkspaceInput, Prisma.WorkSpaceMembersUncheckedCreateWithoutWorkspaceInput> | Prisma.WorkSpaceMembersCreateWithoutWorkspaceInput[] | Prisma.WorkSpaceMembersUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.WorkSpaceMembersCreateOrConnectWithoutWorkspaceInput | Prisma.WorkSpaceMembersCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.WorkSpaceMembersUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.WorkSpaceMembersUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.WorkSpaceMembersCreateManyWorkspaceInputEnvelope
  set?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  disconnect?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  delete?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  connect?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  update?: Prisma.WorkSpaceMembersUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.WorkSpaceMembersUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.WorkSpaceMembersUpdateManyWithWhereWithoutWorkspaceInput | Prisma.WorkSpaceMembersUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.WorkSpaceMembersScalarWhereInput | Prisma.WorkSpaceMembersScalarWhereInput[]
}

export type WorkSpaceMembersUncheckedUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.WorkSpaceMembersCreateWithoutWorkspaceInput, Prisma.WorkSpaceMembersUncheckedCreateWithoutWorkspaceInput> | Prisma.WorkSpaceMembersCreateWithoutWorkspaceInput[] | Prisma.WorkSpaceMembersUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.WorkSpaceMembersCreateOrConnectWithoutWorkspaceInput | Prisma.WorkSpaceMembersCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.WorkSpaceMembersUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.WorkSpaceMembersUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.WorkSpaceMembersCreateManyWorkspaceInputEnvelope
  set?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  disconnect?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  delete?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  connect?: Prisma.WorkSpaceMembersWhereUniqueInput | Prisma.WorkSpaceMembersWhereUniqueInput[]
  update?: Prisma.WorkSpaceMembersUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.WorkSpaceMembersUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.WorkSpaceMembersUpdateManyWithWhereWithoutWorkspaceInput | Prisma.WorkSpaceMembersUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.WorkSpaceMembersScalarWhereInput | Prisma.WorkSpaceMembersScalarWhereInput[]
}

export type WorkSpaceMembersCreateWithoutUserInput = {
  id?: number
  membership_Id?: string
  role?: $Enums.Role
  joinedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutMembersInput
}

export type WorkSpaceMembersUncheckedCreateWithoutUserInput = {
  id?: number
  membership_Id?: string
  role?: $Enums.Role
  joinedAt?: Date | string
  workspaceId: string
}

export type WorkSpaceMembersCreateOrConnectWithoutUserInput = {
  where: Prisma.WorkSpaceMembersWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkSpaceMembersCreateWithoutUserInput, Prisma.WorkSpaceMembersUncheckedCreateWithoutUserInput>
}

export type WorkSpaceMembersCreateManyUserInputEnvelope = {
  data: Prisma.WorkSpaceMembersCreateManyUserInput | Prisma.WorkSpaceMembersCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type WorkSpaceMembersUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.WorkSpaceMembersWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkSpaceMembersUpdateWithoutUserInput, Prisma.WorkSpaceMembersUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.WorkSpaceMembersCreateWithoutUserInput, Prisma.WorkSpaceMembersUncheckedCreateWithoutUserInput>
}

export type WorkSpaceMembersUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.WorkSpaceMembersWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkSpaceMembersUpdateWithoutUserInput, Prisma.WorkSpaceMembersUncheckedUpdateWithoutUserInput>
}

export type WorkSpaceMembersUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.WorkSpaceMembersScalarWhereInput
  data: Prisma.XOR<Prisma.WorkSpaceMembersUpdateManyMutationInput, Prisma.WorkSpaceMembersUncheckedUpdateManyWithoutUserInput>
}

export type WorkSpaceMembersScalarWhereInput = {
  AND?: Prisma.WorkSpaceMembersScalarWhereInput | Prisma.WorkSpaceMembersScalarWhereInput[]
  OR?: Prisma.WorkSpaceMembersScalarWhereInput[]
  NOT?: Prisma.WorkSpaceMembersScalarWhereInput | Prisma.WorkSpaceMembersScalarWhereInput[]
  id?: Prisma.IntFilter<"WorkSpaceMembers"> | number
  membership_Id?: Prisma.StringFilter<"WorkSpaceMembers"> | string
  role?: Prisma.EnumRoleFilter<"WorkSpaceMembers"> | $Enums.Role
  joinedAt?: Prisma.DateTimeFilter<"WorkSpaceMembers"> | Date | string
  workspaceId?: Prisma.StringFilter<"WorkSpaceMembers"> | string
  user_Id?: Prisma.StringFilter<"WorkSpaceMembers"> | string
}

export type WorkSpaceMembersCreateWithoutWorkspaceInput = {
  id?: number
  membership_Id?: string
  role?: $Enums.Role
  joinedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutWorkspaceMembersInput
}

export type WorkSpaceMembersUncheckedCreateWithoutWorkspaceInput = {
  id?: number
  membership_Id?: string
  role?: $Enums.Role
  joinedAt?: Date | string
  user_Id: string
}

export type WorkSpaceMembersCreateOrConnectWithoutWorkspaceInput = {
  where: Prisma.WorkSpaceMembersWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkSpaceMembersCreateWithoutWorkspaceInput, Prisma.WorkSpaceMembersUncheckedCreateWithoutWorkspaceInput>
}

export type WorkSpaceMembersCreateManyWorkspaceInputEnvelope = {
  data: Prisma.WorkSpaceMembersCreateManyWorkspaceInput | Prisma.WorkSpaceMembersCreateManyWorkspaceInput[]
  skipDuplicates?: boolean
}

export type WorkSpaceMembersUpsertWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.WorkSpaceMembersWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkSpaceMembersUpdateWithoutWorkspaceInput, Prisma.WorkSpaceMembersUncheckedUpdateWithoutWorkspaceInput>
  create: Prisma.XOR<Prisma.WorkSpaceMembersCreateWithoutWorkspaceInput, Prisma.WorkSpaceMembersUncheckedCreateWithoutWorkspaceInput>
}

export type WorkSpaceMembersUpdateWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.WorkSpaceMembersWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkSpaceMembersUpdateWithoutWorkspaceInput, Prisma.WorkSpaceMembersUncheckedUpdateWithoutWorkspaceInput>
}

export type WorkSpaceMembersUpdateManyWithWhereWithoutWorkspaceInput = {
  where: Prisma.WorkSpaceMembersScalarWhereInput
  data: Prisma.XOR<Prisma.WorkSpaceMembersUpdateManyMutationInput, Prisma.WorkSpaceMembersUncheckedUpdateManyWithoutWorkspaceInput>
}

export type WorkSpaceMembersCreateManyUserInput = {
  id?: number
  membership_Id?: string
  role?: $Enums.Role
  joinedAt?: Date | string
  workspaceId: string
}

export type WorkSpaceMembersUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  membership_Id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutMembersNestedInput
}

export type WorkSpaceMembersUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  membership_Id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorkSpaceMembersUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  membership_Id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorkSpaceMembersCreateManyWorkspaceInput = {
  id?: number
  membership_Id?: string
  role?: $Enums.Role
  joinedAt?: Date | string
  user_Id: string
}

export type WorkSpaceMembersUpdateWithoutWorkspaceInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  membership_Id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutWorkspaceMembersNestedInput
}

export type WorkSpaceMembersUncheckedUpdateWithoutWorkspaceInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  membership_Id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user_Id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorkSpaceMembersUncheckedUpdateManyWithoutWorkspaceInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  membership_Id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user_Id?: Prisma.StringFieldUpdateOperationsInput | string
}



export type WorkSpaceMembersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  membership_Id?: boolean
  role?: boolean
  joinedAt?: boolean
  workspaceId?: boolean
  user_Id?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workSpaceMembers"]>

export type WorkSpaceMembersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  membership_Id?: boolean
  role?: boolean
  joinedAt?: boolean
  workspaceId?: boolean
  user_Id?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workSpaceMembers"]>

export type WorkSpaceMembersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  membership_Id?: boolean
  role?: boolean
  joinedAt?: boolean
  workspaceId?: boolean
  user_Id?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workSpaceMembers"]>

export type WorkSpaceMembersSelectScalar = {
  id?: boolean
  membership_Id?: boolean
  role?: boolean
  joinedAt?: boolean
  workspaceId?: boolean
  user_Id?: boolean
}

export type WorkSpaceMembersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "membership_Id" | "role" | "joinedAt" | "workspaceId" | "user_Id", ExtArgs["result"]["workSpaceMembers"]>
export type WorkSpaceMembersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type WorkSpaceMembersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type WorkSpaceMembersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $WorkSpaceMembersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorkSpaceMembers"
  objects: {
    workspace: Prisma.$WorkspacePayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    membership_Id: string
    role: $Enums.Role
    joinedAt: Date
    workspaceId: string
    user_Id: string
  }, ExtArgs["result"]["workSpaceMembers"]>
  composites: {}
}

export type WorkSpaceMembersGetPayload<S extends boolean | null | undefined | WorkSpaceMembersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkSpaceMembersPayload, S>

export type WorkSpaceMembersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkSpaceMembersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkSpaceMembersCountAggregateInputType | true
  }

export interface WorkSpaceMembersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorkSpaceMembers'], meta: { name: 'WorkSpaceMembers' } }
  /**
   * Find zero or one WorkSpaceMembers that matches the filter.
   * @param {WorkSpaceMembersFindUniqueArgs} args - Arguments to find a WorkSpaceMembers
   * @example
   * // Get one WorkSpaceMembers
   * const workSpaceMembers = await prisma.workSpaceMembers.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkSpaceMembersFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkSpaceMembersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkSpaceMembersClient<runtime.Types.Result.GetResult<Prisma.$WorkSpaceMembersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorkSpaceMembers that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkSpaceMembersFindUniqueOrThrowArgs} args - Arguments to find a WorkSpaceMembers
   * @example
   * // Get one WorkSpaceMembers
   * const workSpaceMembers = await prisma.workSpaceMembers.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkSpaceMembersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkSpaceMembersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkSpaceMembersClient<runtime.Types.Result.GetResult<Prisma.$WorkSpaceMembersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkSpaceMembers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkSpaceMembersFindFirstArgs} args - Arguments to find a WorkSpaceMembers
   * @example
   * // Get one WorkSpaceMembers
   * const workSpaceMembers = await prisma.workSpaceMembers.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkSpaceMembersFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkSpaceMembersFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkSpaceMembersClient<runtime.Types.Result.GetResult<Prisma.$WorkSpaceMembersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkSpaceMembers that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkSpaceMembersFindFirstOrThrowArgs} args - Arguments to find a WorkSpaceMembers
   * @example
   * // Get one WorkSpaceMembers
   * const workSpaceMembers = await prisma.workSpaceMembers.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkSpaceMembersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkSpaceMembersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkSpaceMembersClient<runtime.Types.Result.GetResult<Prisma.$WorkSpaceMembersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorkSpaceMembers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkSpaceMembersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorkSpaceMembers
   * const workSpaceMembers = await prisma.workSpaceMembers.findMany()
   * 
   * // Get first 10 WorkSpaceMembers
   * const workSpaceMembers = await prisma.workSpaceMembers.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workSpaceMembersWithIdOnly = await prisma.workSpaceMembers.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkSpaceMembersFindManyArgs>(args?: Prisma.SelectSubset<T, WorkSpaceMembersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkSpaceMembersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorkSpaceMembers.
   * @param {WorkSpaceMembersCreateArgs} args - Arguments to create a WorkSpaceMembers.
   * @example
   * // Create one WorkSpaceMembers
   * const WorkSpaceMembers = await prisma.workSpaceMembers.create({
   *   data: {
   *     // ... data to create a WorkSpaceMembers
   *   }
   * })
   * 
   */
  create<T extends WorkSpaceMembersCreateArgs>(args: Prisma.SelectSubset<T, WorkSpaceMembersCreateArgs<ExtArgs>>): Prisma.Prisma__WorkSpaceMembersClient<runtime.Types.Result.GetResult<Prisma.$WorkSpaceMembersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorkSpaceMembers.
   * @param {WorkSpaceMembersCreateManyArgs} args - Arguments to create many WorkSpaceMembers.
   * @example
   * // Create many WorkSpaceMembers
   * const workSpaceMembers = await prisma.workSpaceMembers.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkSpaceMembersCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkSpaceMembersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorkSpaceMembers and returns the data saved in the database.
   * @param {WorkSpaceMembersCreateManyAndReturnArgs} args - Arguments to create many WorkSpaceMembers.
   * @example
   * // Create many WorkSpaceMembers
   * const workSpaceMembers = await prisma.workSpaceMembers.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorkSpaceMembers and only return the `id`
   * const workSpaceMembersWithIdOnly = await prisma.workSpaceMembers.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkSpaceMembersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkSpaceMembersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkSpaceMembersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorkSpaceMembers.
   * @param {WorkSpaceMembersDeleteArgs} args - Arguments to delete one WorkSpaceMembers.
   * @example
   * // Delete one WorkSpaceMembers
   * const WorkSpaceMembers = await prisma.workSpaceMembers.delete({
   *   where: {
   *     // ... filter to delete one WorkSpaceMembers
   *   }
   * })
   * 
   */
  delete<T extends WorkSpaceMembersDeleteArgs>(args: Prisma.SelectSubset<T, WorkSpaceMembersDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkSpaceMembersClient<runtime.Types.Result.GetResult<Prisma.$WorkSpaceMembersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorkSpaceMembers.
   * @param {WorkSpaceMembersUpdateArgs} args - Arguments to update one WorkSpaceMembers.
   * @example
   * // Update one WorkSpaceMembers
   * const workSpaceMembers = await prisma.workSpaceMembers.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkSpaceMembersUpdateArgs>(args: Prisma.SelectSubset<T, WorkSpaceMembersUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkSpaceMembersClient<runtime.Types.Result.GetResult<Prisma.$WorkSpaceMembersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorkSpaceMembers.
   * @param {WorkSpaceMembersDeleteManyArgs} args - Arguments to filter WorkSpaceMembers to delete.
   * @example
   * // Delete a few WorkSpaceMembers
   * const { count } = await prisma.workSpaceMembers.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkSpaceMembersDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkSpaceMembersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkSpaceMembers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkSpaceMembersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorkSpaceMembers
   * const workSpaceMembers = await prisma.workSpaceMembers.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkSpaceMembersUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkSpaceMembersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkSpaceMembers and returns the data updated in the database.
   * @param {WorkSpaceMembersUpdateManyAndReturnArgs} args - Arguments to update many WorkSpaceMembers.
   * @example
   * // Update many WorkSpaceMembers
   * const workSpaceMembers = await prisma.workSpaceMembers.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorkSpaceMembers and only return the `id`
   * const workSpaceMembersWithIdOnly = await prisma.workSpaceMembers.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkSpaceMembersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkSpaceMembersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkSpaceMembersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorkSpaceMembers.
   * @param {WorkSpaceMembersUpsertArgs} args - Arguments to update or create a WorkSpaceMembers.
   * @example
   * // Update or create a WorkSpaceMembers
   * const workSpaceMembers = await prisma.workSpaceMembers.upsert({
   *   create: {
   *     // ... data to create a WorkSpaceMembers
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorkSpaceMembers we want to update
   *   }
   * })
   */
  upsert<T extends WorkSpaceMembersUpsertArgs>(args: Prisma.SelectSubset<T, WorkSpaceMembersUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkSpaceMembersClient<runtime.Types.Result.GetResult<Prisma.$WorkSpaceMembersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorkSpaceMembers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkSpaceMembersCountArgs} args - Arguments to filter WorkSpaceMembers to count.
   * @example
   * // Count the number of WorkSpaceMembers
   * const count = await prisma.workSpaceMembers.count({
   *   where: {
   *     // ... the filter for the WorkSpaceMembers we want to count
   *   }
   * })
  **/
  count<T extends WorkSpaceMembersCountArgs>(
    args?: Prisma.Subset<T, WorkSpaceMembersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkSpaceMembersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorkSpaceMembers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkSpaceMembersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkSpaceMembersAggregateArgs>(args: Prisma.Subset<T, WorkSpaceMembersAggregateArgs>): Prisma.PrismaPromise<GetWorkSpaceMembersAggregateType<T>>

  /**
   * Group by WorkSpaceMembers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkSpaceMembersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkSpaceMembersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkSpaceMembersGroupByArgs['orderBy'] }
      : { orderBy?: WorkSpaceMembersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkSpaceMembersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkSpaceMembersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorkSpaceMembers model
 */
readonly fields: WorkSpaceMembersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkSpaceMembers.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkSpaceMembersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  workspace<T extends Prisma.WorkspaceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkspaceDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorkSpaceMembers model
 */
export interface WorkSpaceMembersFieldRefs {
  readonly id: Prisma.FieldRef<"WorkSpaceMembers", 'Int'>
  readonly membership_Id: Prisma.FieldRef<"WorkSpaceMembers", 'String'>
  readonly role: Prisma.FieldRef<"WorkSpaceMembers", 'Role'>
  readonly joinedAt: Prisma.FieldRef<"WorkSpaceMembers", 'DateTime'>
  readonly workspaceId: Prisma.FieldRef<"WorkSpaceMembers", 'String'>
  readonly user_Id: Prisma.FieldRef<"WorkSpaceMembers", 'String'>
}
    

// Custom InputTypes
/**
 * WorkSpaceMembers findUnique
 */
export type WorkSpaceMembersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkSpaceMembers
   */
  select?: Prisma.WorkSpaceMembersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkSpaceMembers
   */
  omit?: Prisma.WorkSpaceMembersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkSpaceMembersInclude<ExtArgs> | null
  /**
   * Filter, which WorkSpaceMembers to fetch.
   */
  where: Prisma.WorkSpaceMembersWhereUniqueInput
}

/**
 * WorkSpaceMembers findUniqueOrThrow
 */
export type WorkSpaceMembersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkSpaceMembers
   */
  select?: Prisma.WorkSpaceMembersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkSpaceMembers
   */
  omit?: Prisma.WorkSpaceMembersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkSpaceMembersInclude<ExtArgs> | null
  /**
   * Filter, which WorkSpaceMembers to fetch.
   */
  where: Prisma.WorkSpaceMembersWhereUniqueInput
}

/**
 * WorkSpaceMembers findFirst
 */
export type WorkSpaceMembersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkSpaceMembers
   */
  select?: Prisma.WorkSpaceMembersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkSpaceMembers
   */
  omit?: Prisma.WorkSpaceMembersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkSpaceMembersInclude<ExtArgs> | null
  /**
   * Filter, which WorkSpaceMembers to fetch.
   */
  where?: Prisma.WorkSpaceMembersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkSpaceMembers to fetch.
   */
  orderBy?: Prisma.WorkSpaceMembersOrderByWithRelationInput | Prisma.WorkSpaceMembersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkSpaceMembers.
   */
  cursor?: Prisma.WorkSpaceMembersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkSpaceMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkSpaceMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkSpaceMembers.
   */
  distinct?: Prisma.WorkSpaceMembersScalarFieldEnum | Prisma.WorkSpaceMembersScalarFieldEnum[]
}

/**
 * WorkSpaceMembers findFirstOrThrow
 */
export type WorkSpaceMembersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkSpaceMembers
   */
  select?: Prisma.WorkSpaceMembersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkSpaceMembers
   */
  omit?: Prisma.WorkSpaceMembersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkSpaceMembersInclude<ExtArgs> | null
  /**
   * Filter, which WorkSpaceMembers to fetch.
   */
  where?: Prisma.WorkSpaceMembersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkSpaceMembers to fetch.
   */
  orderBy?: Prisma.WorkSpaceMembersOrderByWithRelationInput | Prisma.WorkSpaceMembersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkSpaceMembers.
   */
  cursor?: Prisma.WorkSpaceMembersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkSpaceMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkSpaceMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkSpaceMembers.
   */
  distinct?: Prisma.WorkSpaceMembersScalarFieldEnum | Prisma.WorkSpaceMembersScalarFieldEnum[]
}

/**
 * WorkSpaceMembers findMany
 */
export type WorkSpaceMembersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkSpaceMembers
   */
  select?: Prisma.WorkSpaceMembersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkSpaceMembers
   */
  omit?: Prisma.WorkSpaceMembersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkSpaceMembersInclude<ExtArgs> | null
  /**
   * Filter, which WorkSpaceMembers to fetch.
   */
  where?: Prisma.WorkSpaceMembersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkSpaceMembers to fetch.
   */
  orderBy?: Prisma.WorkSpaceMembersOrderByWithRelationInput | Prisma.WorkSpaceMembersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorkSpaceMembers.
   */
  cursor?: Prisma.WorkSpaceMembersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkSpaceMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkSpaceMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkSpaceMembers.
   */
  distinct?: Prisma.WorkSpaceMembersScalarFieldEnum | Prisma.WorkSpaceMembersScalarFieldEnum[]
}

/**
 * WorkSpaceMembers create
 */
export type WorkSpaceMembersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkSpaceMembers
   */
  select?: Prisma.WorkSpaceMembersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkSpaceMembers
   */
  omit?: Prisma.WorkSpaceMembersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkSpaceMembersInclude<ExtArgs> | null
  /**
   * The data needed to create a WorkSpaceMembers.
   */
  data: Prisma.XOR<Prisma.WorkSpaceMembersCreateInput, Prisma.WorkSpaceMembersUncheckedCreateInput>
}

/**
 * WorkSpaceMembers createMany
 */
export type WorkSpaceMembersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorkSpaceMembers.
   */
  data: Prisma.WorkSpaceMembersCreateManyInput | Prisma.WorkSpaceMembersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorkSpaceMembers createManyAndReturn
 */
export type WorkSpaceMembersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkSpaceMembers
   */
  select?: Prisma.WorkSpaceMembersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkSpaceMembers
   */
  omit?: Prisma.WorkSpaceMembersOmit<ExtArgs> | null
  /**
   * The data used to create many WorkSpaceMembers.
   */
  data: Prisma.WorkSpaceMembersCreateManyInput | Prisma.WorkSpaceMembersCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkSpaceMembersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorkSpaceMembers update
 */
export type WorkSpaceMembersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkSpaceMembers
   */
  select?: Prisma.WorkSpaceMembersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkSpaceMembers
   */
  omit?: Prisma.WorkSpaceMembersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkSpaceMembersInclude<ExtArgs> | null
  /**
   * The data needed to update a WorkSpaceMembers.
   */
  data: Prisma.XOR<Prisma.WorkSpaceMembersUpdateInput, Prisma.WorkSpaceMembersUncheckedUpdateInput>
  /**
   * Choose, which WorkSpaceMembers to update.
   */
  where: Prisma.WorkSpaceMembersWhereUniqueInput
}

/**
 * WorkSpaceMembers updateMany
 */
export type WorkSpaceMembersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorkSpaceMembers.
   */
  data: Prisma.XOR<Prisma.WorkSpaceMembersUpdateManyMutationInput, Prisma.WorkSpaceMembersUncheckedUpdateManyInput>
  /**
   * Filter which WorkSpaceMembers to update
   */
  where?: Prisma.WorkSpaceMembersWhereInput
  /**
   * Limit how many WorkSpaceMembers to update.
   */
  limit?: number
}

/**
 * WorkSpaceMembers updateManyAndReturn
 */
export type WorkSpaceMembersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkSpaceMembers
   */
  select?: Prisma.WorkSpaceMembersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkSpaceMembers
   */
  omit?: Prisma.WorkSpaceMembersOmit<ExtArgs> | null
  /**
   * The data used to update WorkSpaceMembers.
   */
  data: Prisma.XOR<Prisma.WorkSpaceMembersUpdateManyMutationInput, Prisma.WorkSpaceMembersUncheckedUpdateManyInput>
  /**
   * Filter which WorkSpaceMembers to update
   */
  where?: Prisma.WorkSpaceMembersWhereInput
  /**
   * Limit how many WorkSpaceMembers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkSpaceMembersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorkSpaceMembers upsert
 */
export type WorkSpaceMembersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkSpaceMembers
   */
  select?: Prisma.WorkSpaceMembersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkSpaceMembers
   */
  omit?: Prisma.WorkSpaceMembersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkSpaceMembersInclude<ExtArgs> | null
  /**
   * The filter to search for the WorkSpaceMembers to update in case it exists.
   */
  where: Prisma.WorkSpaceMembersWhereUniqueInput
  /**
   * In case the WorkSpaceMembers found by the `where` argument doesn't exist, create a new WorkSpaceMembers with this data.
   */
  create: Prisma.XOR<Prisma.WorkSpaceMembersCreateInput, Prisma.WorkSpaceMembersUncheckedCreateInput>
  /**
   * In case the WorkSpaceMembers was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkSpaceMembersUpdateInput, Prisma.WorkSpaceMembersUncheckedUpdateInput>
}

/**
 * WorkSpaceMembers delete
 */
export type WorkSpaceMembersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkSpaceMembers
   */
  select?: Prisma.WorkSpaceMembersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkSpaceMembers
   */
  omit?: Prisma.WorkSpaceMembersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkSpaceMembersInclude<ExtArgs> | null
  /**
   * Filter which WorkSpaceMembers to delete.
   */
  where: Prisma.WorkSpaceMembersWhereUniqueInput
}

/**
 * WorkSpaceMembers deleteMany
 */
export type WorkSpaceMembersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkSpaceMembers to delete
   */
  where?: Prisma.WorkSpaceMembersWhereInput
  /**
   * Limit how many WorkSpaceMembers to delete.
   */
  limit?: number
}

/**
 * WorkSpaceMembers without action
 */
export type WorkSpaceMembersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkSpaceMembers
   */
  select?: Prisma.WorkSpaceMembersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkSpaceMembers
   */
  omit?: Prisma.WorkSpaceMembersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkSpaceMembersInclude<ExtArgs> | null
}
